version: 0.3
usb:
  mount: /media/removable
  poll_int: 3
  copy_level: all
logging:
  logdir: /var/log/dgs/
serial:
  port: /dev/serial0
  baudrate: 57600
  bytesize: 8
  parity: 'N'
  stopbits: 1
  timeout: 1
signal:
  data_led: 11
  usb_led: 13
  aux_led: 15
