version: 1
disable_existing_loggers: True
formatters:
  data_fmtr:
      format: "%(message)s"
  applog_fmtr:
      format: "%(levelname)s::%(asctime)s (%(funcName)s) - %(message)s"
      datefmt: "%Y-%m-%d - %H:%M:%S"
filters:
  data_filter:
    (): SerialLogger.level_filter
    level : 60

handlers:
  data_hdlr:
    class : logging.handlers.TimedRotatingFileHandler
    formatter : data_fmtr
    filename: /var/log/dgs/gravdata.dat
    when: W6
    backupCount: 30
    encoding: utf-8
    level: 60

  data_size_hdlr:
    class: logging.handlers.RotatingFileHandler
    formatter: data_fmtr
    filename: /var/log/dgs/gravdata-10MB.dat
    maxBytes: 10485760
    encoding: utf-8
    backupCount: 30
    level: 60

  debug_hdlr:
    class: logging.StreamHandler
    formatter: applog_fmtr
    stream: ext://sys.stderr
    level: DEBUG
    filters: [data_filter]

  app_hdlr:
    class: logging.handlers.TimedRotatingFileHandler
    formatter: applog_fmtr
    filename: /var/log/dgs/application.log
    when: MIDNIGHT
    interval: 1
    backupCount: 60
    encoding: utf-8
    level: INFO
    filters: [data_filter]

root:
  level: DEBUG
  handlers: [data_hdlr, data_size_hdlr, debug_hdlr, app_hdlr]
  propogate: True
